
CREATE PROCEDURE DBO.SP_DROPOBJECT  
	@OBJECTNAME VARCHAR(250), @OBJECTTYPE CHAR(1) = NULL 
AS
BEGIN

   SET NOCOUNT ON

   DECLARE @RETURN BIT, @SQL VARCHAR(1000), @WHERENAME VARCHAR(255)
	  , @OBJECT   VARCHAR(255)
	  , @USERNAME VARCHAR(255)
	  , @DBNAME   VARCHAR(255)
	  , @TEMPORARY BIT

   CREATE TABLE #RESULTS ( OBJECTID INT, RAWDATA VARCHAR(256), XTYPE VARCHAR(20) )

   SELECT @OBJECT   = PARSENAME( @OBJECTNAME, 1 )
		 ,@USERNAME = CASE WHEN PATINDEX('%#%',@OBJECT) > 0 THEN '' ELSE ISNULL(PARSENAME( @OBJECTNAME, 2 ) , USER_NAME()) END
		 ,@DBNAME   = CASE WHEN PATINDEX('%#%',@OBJECT) > 0 THEN 'TEMPDB' ELSE ISNULL(PARSENAME( @OBJECTNAME, 3 ),DB_NAME()) END
		 ,@TEMPORARY = CASE WHEN PATINDEX('%##%',@OBJECT) > 0 THEN 2 WHEN PATINDEX('%#%',@OBJECT) > 0 THEN 1 ELSE 0 END

   IF @TEMPORARY = 1
   BEGIN
	  INSERT #RESULTS (OBJECTID, RAWDATA, XTYPE) 
	  SELECT OBJECT_ID('TEMPDB..' + @OBJECT) AS ID, SO.NAME, 'U' AS XTYPE
	  FROM TEMPDB..SYSOBJECTS SO (NOLOCK)
	  WHERE ID = OBJECT_ID('TEMPDB..' + @OBJECT)

	  SELECT @SQL = 'SELECT TOP 1 ID, NAME, XTYPE FROM TEMPDB..SYSOBJECTS (NOLOCK) WHERE NAME = ''' + RAWDATA + ''' AND XTYPE = ''U'' '
	  FROM #RESULTS
   END
   ELSE
   BEGIN
	  SELECT @SQL = 'SELECT TOP 1 ID, NAME, XTYPE FROM ' + @DBNAME + '..SYSOBJECTS (NOLOCK) WHERE NAME = ''' + @OBJECT + ''' AND ( ''' + ISNULL(@OBJECTTYPE,'') + ''' = '' '' OR ''' + ISNULL(@OBJECTTYPE,'') + ''' <> '' '' AND XTYPE = ''' + ISNULL(@OBJECTTYPE,'') + ''' ) '
	  INSERT #RESULTS EXECUTE ( @SQL )
   END

   SELECT @RETURN = ISNULL((SELECT 1 FROM #RESULTS),0)
   IF @RETURN = 1
   BEGIN
	  UPDATE #RESULTS SET 
		 XTYPE = CASE XTYPE
			WHEN 'FN' THEN 'FUNCTION'
			WHEN 'U'  THEN 'TABLE'
			WHEN 'P'  THEN 'PROCEDURE'
			WHEN 'V'  THEN 'VIEW'
			WHEN 'TR'  THEN 'TRIGGER'
		 END,
		 RAWDATA = CASE 
			WHEN XTYPE IN ('FN','P','V','T') THEN @USERNAME + '.' + @OBJECT
			WHEN XTYPE = 'U' AND @TEMPORARY = 0 THEN @DBNAME + '.' + @USERNAME + '.' + RAWDATA
			WHEN XTYPE = 'U' AND @TEMPORARY = 1 THEN RAWDATA
		 END
	  
	  SELECT @SQL = 'IF EXISTS ( ' + @SQL + ') DROP ' + XTYPE + ' ' + @OBJECTNAME FROM #RESULTS
	  EXECUTE ( @SQL )
   END 

   RETURN @RETURN

END
GO