
CREATE PROCEDURE DBO.SP_SEARCHCOMMENT  
(  
	@TEXT VARCHAR(300)  
	, @CURRENTDB INT = 0  
)  
AS  
BEGIN  
	SET NOCOUNT ON  
   
	DECLARE 
		@STRQUERY VARCHAR(1000)  
		, @CRLF CHAR(2)  
		, @CTMAX INT  
		, @DBNAME SYSNAME  
  
	SELECT  @CRLF   = CHAR(13) + CHAR(10)  
  
	EXEC SP_DROPOBJECT #RESULTS   
	CREATE TABLE #RESULTS (DBNAME VARCHAR(30), OBJECTNAME SYSNAME, XTYPE VARCHAR(2))  
  
	IF @CURRENTDB = 1  
	BEGIN  
  
		SELECT @STRQUERY = 'SELECT DB_NAME(), O.NAME, O.XTYPE ' + @CRLF +  
		'FROM SYSOBJECTS O ' + @CRLF +  
		'INNER JOIN SYSCOMMENTS C ON O.ID = C.ID ' + @CRLF +  
		'WHERE C.TEXT LIKE ''%' + @TEXT + '%'''  
  
		--   INSERT INTO #RESULTS  
		--   EXEC(@STRQUERY)
  
		SET @STRQUERY = 'INSERT INTO #RESULTS ' + @STRQUERY
		EXEC (@STRQUERY)
  
	END  
	ELSE  
	BEGIN  
		EXEC SP_DROPOBJECT #DATABASES  
  
		SELECT ROWID = IDENTITY(INT,1,1), DBNAME = NAME  
		INTO #DATABASES  
		FROM MASTER..SYSDATABASES  
  
		SELECT @CTMAX = MAX(ROWID) FROM #DATABASES  
  
		WHILE @CTMAX > 0  
		BEGIN  
			SELECT @STRQUERY = 'SELECT ''' + DBNAME + ''', O.NAME, O.XTYPE ' + @CRLF +  
			'FROM [' + DBNAME + ']..SYSOBJECTS O ' + @CRLF +  
			'INNER JOIN [' + DBNAME + ']..SYSCOMMENTS C ON O.ID = C.ID ' + @CRLF +  
			'WHERE C.TEXT LIKE ''%' + @TEXT + '%'''  
			FROM #DATABASES   
			WHERE ROWID = @CTMAX  
  
			--     INSERT INTO #RESULTS  
			--     EXEC(@STRQUERY)  
 
			SET @STRQUERY = 'INSERT INTO #RESULTS ' + @STRQUERY
			EXEC (@STRQUERY)
  
			SELECT @CTMAX = @CTMAX - 1  
		END  
  
	END  
  
	SELECT DISTINCT DBNAME, XTYPE, OBJECTNAME  
	FROM #RESULTS   
	ORDER BY DBNAME, OBJECTNAME  
  
END  
  

